# For further information on the warnings visit
# https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

default: true

# Allow some exceptions for inline HTML
MD033:
  allowed_elements: ['picture', 'source', 'img']

# Disables need for first line to be a big heading
MD041: false

# Disable line length warnings
MD013: false