name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}
          restore-keys: |
            python-deps-${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

  unit_test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

      - name: Run unit tests
        run: python3 run_tests.py --utest
        continue-on-error: true

      - name: Upload unit test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: reports/utest

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

      - name: Run coverage
        run: python3 run_tests.py --cov
        continue-on-error: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: reports/coverage

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

      - name: Run lint
        run: python3 run_tests.py --lint
        continue-on-error: true

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: reports/pylint

  codestyle:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

      - name: Run pep8 codestyle check
        run: python3 run_tests.py --pep8
        continue-on-error: true

      - name: Upload codestyle report
        uses: actions/upload-artifact@v4
        with:
          name: codestyle-report
          path: reports/codestyle
