name: Publish to Test Pypi

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: python-deps-${{ runner.os }}-${{ hashFiles('setup.py', 'setup.cfg') }}

    # Needed because this is the name of the package on the Test Pypi index
    - name: Add _test to the package name
      run: |
        sed -i 's/PROJECT_NAME = "ankaios_sdk"/PROJECT_NAME = "ankaios_sdk_test"/g' setup.py

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install .[dev]
        pip install twine

    - name: Build package
      run: |
        python3 setup.py sdist bdist_wheel

    - name: Publish package to test Pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
