name: Publish to Pypi

on:
  workflow_call:

jobs:
  publish:
    permissions: write-all
    environment: publish
    runs-on: ubuntu-latest

    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-artifact
        path: dist

    - name: Publish package to Pypi
      uses: pypa/gh-action-pypi-publish@release/v1
